### ISSUE TITLE
Working with Gray scale images

### ISSUE THREAD

**Issue by deepaksivadas** [akanimax/MSG-GAN#11]
Inorder to work with medical gray images, Pls let me know how the code has to be modified. 
I find in_channels & out_channels in GAN.py. Is that to be modified? or in CustomLayers.py?

**Comment by akanimax** [comment]
[This](https://github.com/akanimax/BMSG-GAN/pull/14) might be helpful

**Comment by deepaksivadas** [comment]
Thanks
