### ISSUE TITLE
No FC layers?

### ISSUE THREAD

**Issue by gwern** [akanimax/MSG-GAN#6]
ProGAN, and most GANs, use some fully-connected/dense layers in between the latent z vector and the first CNN/upscaling layers in the Generator. Most strikingly, StyleGAN uses no less than 8 FC layers as part of the 'style mapping' network which is then the input into its Generator.

The graph in the README implies that there's some FC layers (I think; the colors are so similar I can't tell where the FC layers are supposed to be), but they don't seem to be in the code? Looking at the CustomLayers.py's GenInitialBlock, it seems to be pure convolutions, and the printed model arch also seems to not have. Adding them is easy:

```.diff
diff --git a/sourcecode/MSG_GAN/CustomLayers.py b/sourcecode/MSG_GAN/CustomLayers.py
index 381d9f8..bc91929 100644
--- a/sourcecode/MSG_GAN/CustomLayers.py
+++ b/sourcecode/MSG_GAN/CustomLayers.py
@@ -19,9 +19,13 @@ class GenInitialBlock(th.nn.Module):
         :param in_channels: number of input channels to the block
         """
         from torch.nn import LeakyReLU
-        from torch.nn import Conv2d, ConvTranspose2d
+        from torch.nn import Conv2d, ConvTranspose2d, Linear
         super().__init__()
 
+        # from torch.nn import LeakyReLU
+        self.fc1 = th.nn.Linear(in_channels, in_channels)
+        self.fc2 = th.nn.Linear(in_channels, in_channels)
+
         self.conv_1 = ConvTranspose2d(in_channels, in_channels, (4, 4), bias=True)
         self.conv_2 = Conv2d(in_channels, in_channels, (3, 3), padding=(1, 1), bias=True)
 
@@ -34,10 +38,14 @@ class GenInitialBlock(th.nn.Module):
         :param x: input to the module
         :return: y => output
         """
+        x = self.lrelu(self.fc1(x))
+        x = self.lrelu(self.fc2(x))
+
         # convert the tensor shape:
         y = x.view(*x.shape, 1, 1)  # add two dummy dimensions for
         # convolution operation
```

Seems to help training of some anime faces noticeably over the past few hours - although I also added self-attention layers to the D/G so not a clean comparison. Some overnight samples: https://imgur.com/a/CbnaWB0

Since most GANs do that, ProGAN does it and is the mentioned inspiration, and the graph seems to imply you intended to do it, maybe you want to add some fcs somewhere.

**Comment by akanimax** [comment]
Hi @gwern,

I have used a fully connected layer in the DisFinalBlock for giving the final predictions from the extracted features (final 1x1 conv). The first layer of the generator is a transposed conv from `1x1 -> 4x4` which also emulates a dense layer. I just haven't mentioned them explicitly. 
But I do understand your point. Some dense layers in the beginning could really help improve the complexity of the prior and then the generator function could kick in. I'll surely make these changes.
Again thank you for trying out my code and sharing the results. 

BTW, have you tried the StyleGAN yet? I am still reading the paper. Couldn't find their code.
Thank you.

Cheers :beers:!
@akanimax

**Comment by gwern** [comment]
Oh, I see. But I guess that's not enough FCs since adding 2 seems to help. I'm currently trying 4 now.

(It hasn't trained overnight because I was messing around with the self-attention layers since I am a little suspicious of them: some of the parameters, like dividing channels by 8, seem arbitrary and potentially creating artifacts. But anytime I changed the channel count, I couldn't get any stable training. Very odd, perhaps related to the relative positions of the self-attention layers in the G/D and thus their different initial channel counts...)

The StyleGAN code is, sadly, not yet out. I have been checking https://stylegan.xyz/code daily! I am killing time until then. EDIT: now scheduled for January 2019.
