### ISSUE TITLE
about Paper <MSG-GAN>

### ISSUE THREAD

**Issue by Johnson-yue** [akanimax/MSG-GAN#8]
Hi,  I am reading your paper <MSG-GAN> arxiv : 1903.06048v1 .
In your paper the github address is **BMSG-GAN**   but I did not find it in your repos.

**Comment by akanimax** [comment]
Hi @Johnson-yue,

I am glad to know that you are reading my paper. Actually, there is still some work left to be done before publicising the work. The BMSG-GAN repo will be made public soon.

Best regards,
@akanimax

**Comment by Johnson-yue** [comment]
Hi, I see you have a repo as "SMSG-GAN" it means  Self-Attention + MSG-GAN. 
I want to know how performance of SMSG-GAN, is better than basic MSG-GAN ??
