### ISSUE TITLE
about MSG-GAN paper

### ISSUE THREAD

**Issue by Johnson-yue** [akanimax/MSG-GAN#9]
Hi, I look your paper and code of this repo.
This code is not implement : 
  1. PixNorm, 
  2. Equalized Learning Rate ,
  3. Exponential Moving Averaging of Generator Parameters
??? Is it true ?

**Comment by akanimax** [comment]
Hi @Johnson-yue,
Glad to hear from you that you have read the paper. Please note that this is not the repository for the paper's code. The actual repo for the paper is titled BMSG-GAN and will be released soon. Please stay tuned :smile: 
Best regards,
@akanimax
